INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (2, 1, 'Naruto Uzumaki');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (3, 1, 'Sasuke Uchiwa');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (4, 1, 'Sakura Haruno');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (5, 1, 'Jiraya');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (6, 1, 'Kakashi Hatake');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (7, 1, 'Konohamaru Sarutobi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (8, 1, 'Shikamaru Nara');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (9, 1, 'Ino Yamanaka');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (10, 1, 'Chôji Hakimichi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (11, 1, 'Saï');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (12, 1, 'Hinata Hyûga');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (13, 1, 'Kiba Inuzuka');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (14, 1, 'Shino Aburame');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (15, 1, 'Neji Hyûga');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (16, 1, 'Rock Lee');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (17, 1, 'Tenten');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (18, 1, 'Moegi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (19, 1, 'Udon');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (20, 1, 'Hashirama Senju');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (21, 1, 'Tobirama Senju');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (22, 1, 'Hiruzen Sarutobi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (23, 1, 'Minato Namikaze');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (24, 1, 'Tsunade Senju');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (25, 1, 'Danzô Shimura');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (26, 1, 'Orochimaru');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (27, 1, 'Obito Uchiwa');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (28, 1, 'Rin Nohara');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (29, 1, 'Anko Mitarashi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (30, 1, 'Shikaku Nara');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (31, 1, 'Shizune');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (32, 1, 'Asuma Sarutobi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (33, 1, 'Gaï Maito');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (34, 1, 'Kurenai Yûhi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (35, 1, 'Meï Terumi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (36, 1, 'Chôjûrô');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (37, 1, 'Ao');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (38, 1, 'Utakata');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (39, 1, 'A');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (40, 1, 'Darui');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (41, 1, 'Samui');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (42, 1, 'Omoï');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (43, 1, 'Karui');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (44, 1, 'Killer Bee');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (45, 1, 'Yugito Nii');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (46, 1, 'Kinkaku');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (47, 1, 'Ginkaku');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (48, 1, 'Jirôbô');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (49, 1, 'Kidômaru');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (50, 1, 'Sakon & Ukon');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (51, 1, 'Tayuya');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (52, 1, 'Kimimaro Kaguya');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (53, 1, 'Kabuto Yakushi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (54, 1, 'Suigetsu Hôzuki');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (55, 1, 'Karin Uzumaki');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (56, 1, 'Jûgo');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (57, 1, 'Gaara Sabaku');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (58, 1, 'Temari Sabaku');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (59, 1, 'Kankurô Sabaku');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (60, 1, 'Chiyo');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (61, 1, 'Pakura');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (62, 1, 'Rasa Sabaku');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (63, 1, 'Mû');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (64, 1, 'Onoki');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (65, 1, 'Kurotsuchi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (66, 1, 'Akatsuchi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (67, 1, 'Rôshi');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (68, 1, 'Han');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (69, 1, 'Hanzô');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (70, 1, 'Kushina Uzumaki');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (71, 1, 'Mifune');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (72, 1, 'Itachi Uchiwa');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (73, 1, 'Kisame Hoshigaki');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (74, 1, 'Zestu');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (75, 1, 'Deidara');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (76, 1, 'Sasori');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (77, 1, 'Hidan');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (78, 1, 'Kakuzu');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (79, 1, 'Konan');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (80, 1, 'Pain');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (81, 1, 'Nagato');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (82, 1, 'Yahiko');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (83, 1, 'Konan');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (84, 1, 'Fû');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (85, 1, 'Madara Uchiwa');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (86, 1, 'Haku');
INSERT INTO `characters` (`id`, `universe_id`, `name`) VALUES (87, 1, 'Zabuza Momochi');



/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2020-01-28 15:38:14
